### ISSUE TITLE
Loss is nan

### ISSUE THREAD

**Issue by SebasJoustra** [ShahzaibWaseem/SpatialPyramidPooling_tf2#1]
Hi,

I was looking for a TF2.0+ SPP implementation and found your project. I am not sure whether this project was finished or not, but I am having issues when using the SPP layer.

The problem is that the loss (training/validation) is always ```nan``` when fitting the data, so the weights are not propely updating. I also tried running your runner.py which has the same problem:

```
Epoch 1/10
60000/60000 [==============================] - 12s 200us/sample - loss: nan - accuracy: 0.0987
Epoch 2/10
60000/60000 [==============================] - 9s 158us/sample - loss: nan - accuracy: 0.0987
Epoch 3/10
60000/60000 [==============================] - 10s 162us/sample - loss: nan - accuracy: 0.0987
Epoch 4/10
60000/60000 [==============================] - 10s 159us/sample - loss: nan - accuracy: 0.0987
Epoch 5/10
60000/60000 [==============================] - 10s 158us/sample - loss: nan - accuracy: 0.0987
```

Did you ever get it working?

Thanks!

**Comment by YulongXia** [comment]
the value of convolution kernel 3rd dim should be equal with NUM_CHANNELS

NUM_CHANNELS = 1
model.add(Convolution2D(32, 3, 3, padding='same', input_shape=(None, None, NUM_CHANNELS)))

should be

NUM_CHANNELS = 1
model.add(Convolution2D(32, 3, NUM_CHANNELS, padding='same', input_shape=(None, None, NUM_CHANNELS)))

**Comment by ShahzaibWaseem** [comment]
Yes, That is correct.
I have updated the code.
Thank you @YulongXia .

**Comment by YulongXia** [comment]
> Yes, That is correct.
> I have updated the code.
> Thank you @YulongXia .

I'm so sorry. I think I make a mistake. I find that the NAN error come back when I set NUM_CHANNELS = 3.  After debugging, I find that the shape of input of SPP net is (batch_size,1,1,the NUM of last CONV2D's filters), which means the num_rows ,num_ cols shrink to 1. So I view the docment of Convolution2D and I know that the 3rd param represents stride. if the stride is greater than 1 , the output's shape of Convolution2D will be shrink, right? 
So remove the 3rd param to fix the bug.
like this: 
NUM_CHANNELS = 1
model.add(Convolution2D(32, 3, 3, padding='same', input_shape=(None, None, NUM_CHANNELS)))

should be

NUM_CHANNELS = 1
model.add(Convolution2D(32, 3, padding='same', input_shape=(None, None, NUM_CHANNELS)))
